Add Enhanced Documentation
showalrm/sn-machine pull request #21
Opened 2018-12-10 17:56 UTC by coledn

Tell me what to fix please.

2018-12-10 18:01 UTC, showalter requested changes

2018-12-10 18:01 UTC, showalter commented on README.md
> +cells and the number of Memory cells they would like. The user may choose between 1-16 register cells
Don't capitalize memory

2018-12-10 18:01 UTC, showalter commented on README.md
> +and 0-255 memory cells.
0 cells isn't an option, and 256 is.

2018-12-10 18:01 UTC, showalter commented on README.md
> +After the user's cells are chosen the user may edit the contents of the register cell with "R"
This is a great place for a list.

2018-12-10 18:01 UTC, showalter commented on __main__.py
> +
There should be two lines between functions rather than three

2018-12-10 18:01 UTC, showalter commented on __main__.py
> +        instruction (str):
Add a description

2018-12-10 18:01 UTC, showalter commented on display.py
> +        The complete description
type?

2018-12-10 18:01 UTC, showalrm commented on processor.py
> +        """Values will be returned as base 16 int.
There's a return here

2018-12-10 18:01 UTC, showalrm commented on processor.py
> +
There should be a parameter here.

2018-12-10 19:34 UTC, showalter requested changes
Docstrings for each module and the cell class should be added

2018-12-10 19:37 UTC, showalrm commented on __main__.py
> +        instruction (str): the instruction being executed in this case starts with a 2
This is awkward working

2018-12-10 19:38 UTC, showalrm commented on README.md
> +### Language Description Table
We should really clarify that opcode 6 does the same thing as 5 for now.

2018-12-10 19:55 UTC, showalrm commented on README.md
> +|6         | RST     | ADD the bit patterns in registers S and T and put the result in register R in a floating-point notation (**NOTE** Op-Code 6 does the same as 5)|
clarify that for now, it is the same operation, and that floating point addition is not available.

2018-12-10 19:57 UTC, showalrm commented on processor.py
> +        Return:
returns

2018-12-10 19:57 UTC, showalrm commented on processor.py
> +            int: an integer representation of the cells contents
cell's

2018-12-10 19:58 UTC, showalrm commented on processor.py
> +        """Values will be returned as base 16 int.
This should be a description, not just a technicality on how to use the function.

2018-12-10 19:58 UTC, showalrm commented on processor.py
> +        """Values must be passed as a string representation of a hex value
This should be a description

2018-12-10 20:34 UTC, coledn commented on processor.py
> +            int: an integer representation of the cells contents
what do you mean by cells???

2018-12-10 21:41 UTC, showalrm commented on __main__.py
> +        instruction (str): instruction (str): the instruction being executed, in this case it starts with a 1
delete duplicate

2018-12-11 16:19 UTC, showalter requested changes
Most of this looks good so far, but I'd like for each module and the Cell class to have a docstring as well.

2018-12-11 16:19 UTC, showalrm commented on processor.py
> +        (The value must be passed as a hexadecimal value or as a string
Parentheses should not be used here, and I'd suggest adding a newline between the description and the extra information.

2018-12-12 02:44 UTC, showalter requested changes

2018-12-12 02:44 UTC, showalrm commented on __main__.py
> +"""The main file contains the main function and other functions for constructing cells and executing machine code
Each module string should have a little more substance than this. A copyright notice should be here. Also, module attributes, such as registers, cells, and icounter, should have descriptions in the module docstring or directly below each of those attributes.

2018-12-12 02:44 UTC, showalrm commented on __main__.py
> +    """If instruction looks like 2RXY
Can we move each of the "if instruction looks like ..." to a different line?
Example:
```Load a register R with the bit pattern XY

Instruction should look like (opcode)RXY
...
```

If we want to change the opcodes later, it's easier to just say (opcode) now than changing all of the comments later.

2018-12-12 02:44 UTC, showalrm commented on __main__.py
> +
only have one empty line

2018-12-12 02:44 UTC, showalrm commented on __main__.py
> +
I think you can move the ending quotes up here

2018-12-12 02:44 UTC, showalrm commented on processor.py
> +        """Returns the string representation of the ID
Indentation and whitespace

2018-12-12 02:44 UTC, showalrm commented on processor.py
> +        """Constructs and intializes the id and value for a cell
whitespace

2018-12-12 02:44 UTC, showalrm commented on processor.py
> +        """Returns the a string reorientation of the contents of the cell.
whitespace

2018-12-12 20:25 UTC, nuttercd reviewed
These changes are good.

2018-12-12 20:36 UTC, showalter approved these changes

2018-12-12 20:36 UTC, merged